name: Docs CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: "templates/**/*.md standards/**/*.md README.md"
      - name: Check PR body has normative reference
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.info('No pull request payload detected; skipping normative reference check.');
              return;
            }
            const { owner, repo } = context.repo;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner,
                repo,
                pull_number: pr.number,
                per_page: 100,
              },
            );
            const touchesNormative = files.some((file) => /^(templates|standards)\//.test(file.filename));
            if (!touchesNormative) {
              core.info('No templates/standards files changed; skipping normative block enforcement.');
              return;
            }
            const body = pr.body || "";
            const ok = /Référence normative.*(ISO|ISTQB|IEEE|IREB|25010|29119)/i.test(body);
            if (!ok) core.setFailed("La PR doit contenir un bloc 'Référence normative'.");
